# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clickrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickrecords',
            name='read_ts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
