# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clickrecords_read_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendset',
            name='read_ts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
